"""Export the V5 design screens to the website.

Runs the screen generators (not the canvas-only flow boards), then writes one small JS module per screen to
apps/web/v5/screens/, plus the shared stylesheet. The site renders these with <Screen>, which swaps links for
routes, {{values}} for live state and [data-slot] elements for React components.

  python3.13 export_web.py            # every screen
  python3.13 export_web.py v5u_unsent v5m_capcare   # only these generator modules (faster, fewer files touched)
"""
import io, os, sys, json, runpy, contextlib
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
os.chdir(HERE)
import gen5

ALL = ['v5_brand', 'v5_arrival', 'v5_home', 'v5_burn', 'v5_leave', 'v5_talk', 'v5x_echo', 'v5x_talk', 'v5x_voice', 'v5x_system',
       'v5x_legal', 'v5m_home', 'v5m_arrival', 'v5m_burnecho', 'v5m_capcare', 'v5m_talk', 'v5m_voice', 'v5m_system',
       'v5e_leave', 'v5e_talk', 'v5e_system', 'v5u_unsent']
WEB = os.path.join(HERE, '..', '..', 'apps', 'web', 'v5')
SCREENS = os.path.join(WEB, 'screens')
os.makedirs(SCREENS, exist_ok=True)

only = sys.argv[1:]
mods = ALL
# modules import each other; run everything so PAGES is complete, but only write screens from the asked modules
written_by = {}
for m in mods:
    before = set(gen5.PAGES)
    with contextlib.redirect_stdout(io.StringIO()):
        runpy.run_path(m + '.py', run_name='__main__')
    for k in gen5.PAGES:
        if k not in before:
            written_by.setdefault(k, m)
    # a module may re-define a page another module made earlier: the last writer wins, like on the canvas
    for k, v in gen5.PAGES.items():
        if k in before and v is not None:
            pass

def export(name, p):
    cfg = gen5.SOUND.get(name, {})
    body = p['body']
    if cfg:
        body = gen5.snd_marker(cfg) + gen5.tag_sound(cfg, body)
    mod = {
        'name': name, 'title': p['title'], 'w': p['w'], 'h': p['h'], 'bg': p['bg'],
        'phone': p['w'] == gen5.MW, 'css': p['css'] or '', 'html': body.strip(),
    }
    src = '// generated by design/v5/export_web.py — edit the generator, not this file\nexport default ' + json.dumps(mod, ensure_ascii=False) + ';\n'
    path = os.path.join(SCREENS, name + '.js')
    old = open(path).read() if os.path.exists(path) else None
    if old != src:
        open(path, 'w').write(src)
        return True
    return False

changed = 0
names = []
for name, p in gen5.PAGES.items():
    if not name.startswith('V5'):
        continue
    if only and written_by.get(name) not in only:
        continue
    names.append(name)
    changed += export(name, p)

if not only:
    base = gen5.BASE_CSS + '\n.flare,.leak,.nglow,.dawn,.dawnrise,.bloom,.glowring{display:none !important}\n'
    open(os.path.join(WEB, 'base.css'), 'w').write('/* generated by design/v5/export_web.py */\n' + base)
    # an index of every screen and its size, so pages can pick the phone / desktop variant
    idx = {n: {'w': p['w'], 'h': p['h'], 'phone': p['w'] == gen5.MW} for n, p in gen5.PAGES.items() if n.startswith('V5')}
    open(os.path.join(WEB, 'index.json'), 'w').write(json.dumps(idx, indent=0))
print(f'{len(names)} screens checked, {changed} written')
