"""N0TRACE V5 — the live pieces of the pods (chat lines, room slips, stage cards…) as HTML templates for the site.

Pod screens hold real conversations and real rooms, so the site can't use the boards' sample lines. This writes the
same markup the generators draw, with {{tokens}} where live values go and <sc-if value="{{x}}"> for optional bits.
The site fills them in (apps/web/app/talk/_pods/Part.js).

  cd design/v5 && python3.13 v5_pods_parts.py      # writes apps/web/app/talk/_pods/parts.gen.js
"""
import io, os, json, contextlib, re
from gen5 import *
with contextlib.redirect_stdout(io.StringIO()):
    import v5x_voice as VX
    import v5m_voice as MV
    import v5e_talk as ET
    import v5m_talk as MT

OUTJS = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'apps', 'web', 'app', 'talk', '_pods', 'parts.gen.js')

def nomsg(h):
    """Live lines appear one at a time: no staggered entrance delay."""
    return h.replace('--i:0;', '--i:0;').replace('class="msg"', 'class="msg live"')

def act(h, label, name):
    """href="#" + words -> data-act."""
    return re.sub(r'<a href="#"', f'<a href="#" data-act="{name}"', h, count=1) if label in h else h

P = {}
# ---- desktop chat lines (v5x_voice / v5e_talk) ----
P['dMine'] = nomsg(VX.line_msg('{{text}}', True, t='{{t}}'))
P['dTheirs'] = nomsg(VX.line_msg('{{text}}', False, who='{{partner}}', t='{{t}}'))
P['dSys'] = nomsg(VX.sys_line('{{text}}'))
P['dTyping'] = VX.typing('{{partner}}')
P['dFail'] = act(nomsg(ET.fail_line('{{text}}', '{{t}}')), 'try again', 'retry')
P['dPencil'] = nomsg(ET.pencil_line('{{text}}'))
P['dFirst'] = nomsg(ET.pencil_line('{{text}}'))
# ---- phone chat lines (v5m_voice / v5e_talk) ----
P['mMine'] = nomsg(MV.mmsg('{{text}}', True, t='{{t}}'))
P['mTheirs'] = nomsg(MV.mmsg('{{text}}', False, who='{{partner}}', t='{{t}}'))
P['mSys'] = nomsg(MV.msys('{{text}}'))
P['mTyping'] = MV.mtyping('{{partner}}')
P['mFail'] = act(nomsg(ET.fail_line('{{text}}', '{{t}}', phone=True)), 'try again', 'retry')
P['mPencil'] = nomsg(ET.pencil_line('{{text}}', phone=True))
P['mFirst'] = P['mPencil']

CSS = ET.EXTRA_CSS + """
.msg.live{animation-delay:0s !important}
"""

def write():
    os.makedirs(os.path.dirname(OUTJS), exist_ok=True)
    src = ('// generated by design/v5/v5_pods_parts.py — edit the generator, not this file\n'
           f'export const CSS = {json.dumps(CSS, ensure_ascii=False)};\n'
           f'export default {json.dumps(P, ensure_ascii=False)};\n')
    open(OUTJS, 'w').write(src)
    print(f'{len(P)} parts written')

if __name__ == '__main__':
    write()
