import Legal, { S } from '@/components/Legal';

export const metadata = { title: 'Privacy · wisp' };

export default function Privacy() {
  return (
    <Legal title="PRIVACY" blurb="PLAIN LANGUAGE. NO ACCOUNTS MEANS THERE IS VERY LITTLE TO SAY." other="TERMS">
      <S h="THE SHORT VERSION">
        <p className="big">WE DON&apos;T KNOW WHO YOU ARE. WHAT LITTLE EXISTS WHILE YOU&apos;RE HERE LIVES IN SERVER MEMORY AND IS GONE WHEN YOU LEAVE OR THE SERVER RESTARTS.</p>
      </S>
      <S h="WHAT EXISTS WHILE YOU'RE CONNECTED">
        <dl className="facts">
          <dt>PSEUDONYM</dt><dd>RANDOMLY GENERATED, LIKE <span className="nc">quiet_otter_42</span>.</dd>
          <dt>SESSION KEY</dt><dd>A RANDOM CODE IN YOUR TAB SO A SHORT DROP DOESN&apos;T COST YOU YOUR SEAT. GONE WHEN YOU CLOSE THE TAB.</dd>
          <dt>ROOM ROLE</dt><dd>LISTENER, SPEAKER OR MOD, AND HOW LONG YOU&apos;VE BEEN ON STAGE.</dd>
          <dt>MESSAGES</dt><dd>1:1 MESSAGES ARE PASSED TO YOUR MATCH ONLY. ROOM CHAT IS HELD IN MEMORY WHILE THE ROOM HAS PEOPLE IN IT, THEN DROPPED.</dd>
          <dt>REPORT COUNTS</dt><dd>HOW MANY PEOPLE REPORTED A SESSION. USED TO REMOVE PEOPLE AUTOMATICALLY.</dd>
        </dl>
      </S>
      <S h="WHERE IT LIVES">
        <p>IN MEMORY ON OUR SIGNALING SERVER. THERE IS NO DATABASE. WE DON&apos;T WRITE ANY OF IT TO DISK, AND WE DON&apos;T LOG WHAT PEOPLE SAY.</p>
      </S>
      <S h="VOICE">
        <p>VOICE IS PEER TO PEER (WEBRTC). YOUR AUDIO GOES STRAIGHT TO THE OTHER PEOPLE IN THE ROOM OR CALL, ENCRYPTED, NOT THROUGH OUR SERVER. BECAUSE THE CONNECTION IS DIRECT, THEIR DEVICES CAN SEE YOUR IP ADDRESS. WHEN A DIRECT CONNECTION ISN&apos;T POSSIBLE, THE ENCRYPTED AUDIO MAY BE RELAYED THROUGH CLOUDFLARE, WHO CAN&apos;T LISTEN TO IT. WE NEVER RECORD AUDIO.</p>
      </S>
      <S h="OPT-IN ONLY">
        <p>&quot;REMEMBER ME&quot; SAVES YOUR PSEUDONYM IN YOUR BROWSER&apos;S LOCAL STORAGE, ON YOUR DEVICE. NOT ON OUR SIDE. CLEAR YOUR BROWSER DATA, OR USE A PRIVATE WINDOW, AND YOU GET A FRESH NAME EVERY TIME AGAIN.</p>
      </S>
      <S h="NOT COLLECTED">
        <p>NO ACCOUNTS. NO EMAIL OR PHONE NUMBER. NO PASSWORDS. NO PAYMENT INFORMATION. NO COOKIES. NO ANALYTICS RIGHT NOW. IF THAT CHANGES, THIS PAGE CHANGES FIRST.</p>
      </S>
      <S h="SERVICES WE USE">
        <p>THE SITE IS HOSTED ON VERCEL AND THE SERVER ON NORTHFLANK. TO SET UP VOICE CONNECTIONS, YOUR BROWSER CONTACTS PUBLIC STUN SERVERS RUN BY CLOUDFLARE AND GOOGLE. ALL OF THESE SEE YOUR IP ADDRESS, AND EACH HAS ITS OWN PRIVACY POLICY.</p>
      </S>
      <S h="AGE">
        <p>WISP IS FOR PEOPLE 18 AND OVER.</p>
      </S>
    </Legal>
  );
}
