import Legal, { S } from '@/components/Legal';

export const metadata = { title: 'Terms · wisp' };

const DONT = [
  'HARASS, THREATEN OR BULLY ANYONE.',
  "POST HATE SPEECH OR SEXUAL CONTENT DIRECTED AT PEOPLE WHO DIDN'T ASK FOR IT.",
  "SHARE ANYONE'S PERSONAL INFORMATION, OR TRY TO UNMASK THEM.",
  "RECORD A CONVERSATION WITHOUT EVERYONE'S CONSENT.",
  'SPAM, SCAM, ADVERTISE OR RUN BOTS.',
  'DO ANYTHING ILLEGAL, OR TRY TO BREAK OR OVERLOAD THE SERVICE.'
];

export default function Terms() {
  return (
    <Legal title="TERMS" blurb="THE RULES FOR USING WISP. SHORT ON PURPOSE." other="PRIVACY">
      <S h="THE SHORT VERSION">
        <p className="big">BE 18 OR OLDER. TREAT STRANGERS LIKE PEOPLE. IF YOU DON&apos;T, THE ROOM AND THE REPORT BUTTON WILL SORT IT OUT.</p>
      </S>
      <S h="01 WHO CAN USE WISP">
        <p>YOU MUST BE AT LEAST 18. BY CONFIRMING THE AGE CHECK YOU&apos;RE TELLING US YOU ARE. IF YOU AREN&apos;T, DON&apos;T USE WISP.</p>
      </S>
      <S h="02 DON'T">
        <dl className="rules">
          {DONT.flatMap((d, i) => [<dt key={`t${i}`}>—</dt>, <dd key={`d${i}`}>{d}</dd>])}
        </dl>
      </S>
      <S h="03 MODERATION">
        <p>ROOMS ARE MODERATED BY THEIR OWN MEMBERS. THE FIRST TWO PEOPLE IN A ROOM ARE ITS MODS, AND ANYONE WHO SPENDS 2:30 ON STAGE BECOMES ONE TOO. LISTENERS CAN RAISE A HAND TO ASK FOR THE STAGE. ONLY MODS DECIDE WHO SPEAKS: THEY CAN ACCEPT OR DECLINE RAISED HANDS, INVITE LISTENERS UP, AND MOVE SPEAKERS BACK TO LISTENERS, BUT NOT OTHER MODS. ANYONE CAN REPORT ANYONE. WHEN ENOUGH DIFFERENT PEOPLE REPORT THE SAME PERSON, THEY&apos;RE REMOVED AUTOMATICALLY, MODS INCLUDED. IN 1:1 CHAT, THREE REPORTS FROM DIFFERENT PEOPLE REMOVE SOMEONE FROM MATCHMAKING. WE CAN ALSO BLOCK ACCESS WHEN WE NEED TO.</p>
      </S>
      <S h="04 WHAT YOU SAY">
        <p>WHAT YOU SAY IS YOURS, AND YOU&apos;RE RESPONSIBLE FOR IT. WE DON&apos;T STORE IT. REMEMBER THAT THE PERSON ON THE OTHER SIDE IS A STRANGER. DON&apos;T SHARE ANYTHING YOU WOULDN&apos;T WANT REPEATED.</p>
      </S>
      <S h="05 NO GUARANTEES">
        <p>WISP IS PROVIDED AS IS. IT MAY GO DOWN, CHANGE OR STOP. WE&apos;RE NOT RESPONSIBLE FOR WHAT OTHER PEOPLE SAY OR DO ON IT.</p>
      </S>
      <S h="06 CHANGES">
        <p>IF THESE TERMS CHANGE, THE DATE AT THE TOP CHANGES TOO. USING WISP AFTER THAT MEANS YOU ACCEPT THE NEW VERSION.</p>
      </S>
      <S h="07 GOVERNING LAW">
        <p>THESE TERMS ARE GOVERNED BY THE LAWS OF INDIA.</p>
      </S>
    </Legal>
  );
}
